### PR TITLE
It's `import` now.

### PR DESCRIPTION
**Pull request by impinball**

### CODE REVIEW

**Comment by tcoopman** [comment]
Does this work without updating the dependencies?
I haven't used browserify in a while (using webpack) but I believe to use `import` es6ify should also be updated?

**Comment by impinball** [comment]
Probably, which also implies the repo is very out of date as well. I'll append that to the PR.

**Comment by impinball** [comment]
es6ify is at v1.6

**Comment by tcoopman** [comment]
Thanks

**Pull request merged**
